name: landslide_usecase
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pymt
  - cdsapi
  - pymt_topography
  - numpy
  - xesmf
  - xarray
  - rioxarray
  - cftime
  - imageio
  - matplotlib
  - jupyter
  - pip
  - pip:
    - pymt-era5
    - imageio_ffmpeg

